# Generated by Django 6.1.1 on 2026-09-10 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Rol',
            fields=[
                ('id_rol', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(choices=[('Administrador', 'Administrador'), ('Supervisor', 'Supervisor'), ('JefaManipuladoras', 'Jefa de Manipuladoras'), ('Manipuladora', 'Manipuladora de alimentos')], max_length=30, unique=True)),
                ('descripcion', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Rol',
                'verbose_name_plural': 'Roles',
                'db_table': 'roles',
            },
        ),
    ]
