# Generated by Django 6.1.1 on 2026-09-11 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roles', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='rol',
            options={},
        ),
        migrations.AlterField(
            model_name='rol',
            name='nombre',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
