# Generated by Django 6.1.1 on 2026-10-01 04:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roles', '0002_alter_rol_options_alter_rol_nombre'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='rol',
            options={'verbose_name': 'Rol', 'verbose_name_plural': 'Roles'},
        ),
        migrations.AlterField(
            model_name='rol',
            name='nombre',
            field=models.CharField(choices=[('Administrador', 'Administrador'), ('supervisor', 'supervisor'), ('JefaManipuladoras', 'Jefa de Manipuladoras'), ('Manipuladora', 'Manipuladora de alimentos')], max_length=30, unique=True),
        ),
    ]
