# Generated by Django 6.0.7 on 2026-09-12 03:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asistencia_diaria', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asistenciadiaria',
            name='id_usuario_manipuladora',
            field=models.IntegerField(blank=True, db_column='id_usuario_manipuladorajefe', null=True),
        ),
    ]
