# Generated by Django 6.1.1 on 2026-09-10 20:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('secciones_menu', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Plato',
            fields=[
                ('id_plato', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=150, verbose_name='Nombre del plato')),
                ('descripcion', models.TextField(blank=True, null=True, verbose_name='Descripción')),
                ('precio', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Precio / Costo')),
                ('imagen', models.CharField(blank=True, max_length=255, null=True, verbose_name='URL o ruta de imagen')),
                ('activo', models.BooleanField(default=True, verbose_name='¿Está activo?')),
                ('id_seccion_menu', models.ForeignKey(blank=True, db_column='id_seccion_menu', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='platos', to='secciones_menu.seccionmenu', verbose_name='Sección del Menú')),
            ],
            options={
                'verbose_name': 'Plato',
                'verbose_name_plural': 'Platos',
                'db_table': 'platos',
            },
        ),
    ]
