# Generated by Django 6.1.1 on 2026-09-12 08:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('platos', '0001_initial'),
        ('secciones_menu', '0002_alter_seccionmenu_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='plato',
            options={},
        ),
        migrations.RemoveField(
            model_name='plato',
            name='activo',
        ),
        migrations.RemoveField(
            model_name='plato',
            name='descripcion',
        ),
        migrations.RemoveField(
            model_name='plato',
            name='id_seccion_menu',
        ),
        migrations.RemoveField(
            model_name='plato',
            name='imagen',
        ),
        migrations.RemoveField(
            model_name='plato',
            name='nombre',
        ),
        migrations.RemoveField(
            model_name='plato',
            name='precio',
        ),
        migrations.AddField(
            model_name='plato',
            name='componente',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='plato',
            name='id_seccion',
            field=models.ForeignKey(blank=True, db_column='id_seccion', null=True, on_delete=django.db.models.deletion.SET_NULL, to='secciones_menu.seccionmenu'),
        ),
        migrations.AddField(
            model_name='plato',
            name='nombre_plato',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
