# Generated by Django 6.1.1 on 2026-09-16 00:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('platos', '0002_alter_plato_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='plato',
            options={'managed': True, 'verbose_name': 'Plato', 'verbose_name_plural': 'Platos'},
        ),
    ]
