# Generated by Django 6.1.1 on 2026-09-16 00:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('platos', '0003_alter_plato_options'),
        ('secciones_menu', '0003_alter_seccionmenu_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='plato',
            name='activo',
        ),
        migrations.RemoveField(
            model_name='plato',
            name='descripcion',
        ),
        migrations.RemoveField(
            model_name='plato',
            name='id_seccion_menu',
        ),
        migrations.RemoveField(
            model_name='plato',
            name='imagen',
        ),
        migrations.RemoveField(
            model_name='plato',
            name='nombre',
        ),
        migrations.RemoveField(
            model_name='plato',
            name='precio',
        ),
        migrations.AddField(
            model_name='plato',
            name='componente',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='plato',
            name='id_seccion',
            field=models.ForeignKey(blank=True, db_column='id_seccion', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='secciones_menu.seccionmenu'),
        ),
        migrations.AddField(
            model_name='plato',
            name='nombre_plato',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
