# Generated by Django 6.1.1 on 2026-10-01 04:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('platos', '0004_remove_plato_activo_remove_plato_descripcion_and_more'),
        ('secciones_menu', '0004_alter_seccionmenu_id_jornada'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plato',
            name='id_seccion',
            field=models.ForeignKey(blank=True, db_column='id_seccion', db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='secciones_menu.seccionmenu'),
        ),
    ]
