# Generated by Django 6.1.1 on 2026-10-01 04:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ingredientes', '0002_remove_ingrediente_id_and_more'),
        ('movimientos_inventario', '0001_initial'),
        ('unidades_medida', '0006_alter_unidadmedida_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='movimientoinventario',
            name='cantidad',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='movimientoinventario',
            name='fecha',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='movimientoinventario',
            name='id_ingrediente',
            field=models.ForeignKey(db_column='id_ingrediente', on_delete=django.db.models.deletion.CASCADE, to='ingredientes.ingrediente'),
        ),
        migrations.AlterField(
            model_name='movimientoinventario',
            name='id_unidad_medida',
            field=models.ForeignKey(db_column='id_unidad_medida', on_delete=django.db.models.deletion.PROTECT, to='unidades_medida.unidadmedida'),
        ),
        migrations.AlterField(
            model_name='movimientoinventario',
            name='id_usuario_manipuladora',
            field=models.ForeignKey(blank=True, db_column='id_usuario_manipuladora', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='movimientoinventario',
            name='observaciones',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='movimientoinventario',
            name='tipo_movimiento',
            field=models.CharField(max_length=50),
        ),
    ]
