# Generated by Django 6.1.1 on 2026-09-10 20:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('roles', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id_usuario', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('apellido', models.CharField(max_length=100)),
                ('email', models.EmailField(db_column='correo', max_length=254)),
                ('password', models.CharField(max_length=128)),
                ('documento_identidad', models.CharField(db_column='numero_documento', max_length=20)),
                ('tipo_documento', models.CharField(max_length=10)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_superuser', models.BooleanField(default=False)),
                ('last_login', models.DateTimeField(blank=True, null=True)),
                ('id_rol', models.ForeignKey(db_column='rol_id', on_delete=django.db.models.deletion.DO_NOTHING, to='roles.rol')),
            ],
            options={
                'db_table': 'usuarios',
            },
        ),
    ]
