# Generated by Django 6.1.1 on 2026-09-12 08:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0002_rol_alter_usuario_options'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Rol',
        ),
        migrations.AlterModelOptions(
            name='usuario',
            options={},
        ),
    ]
