# Generated by Django 6.1.1 on 2026-10-01 04:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jornadas', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='jornada',
            options={'managed': False},
        ),
    ]
