# Generated by Django 6.0.6 on 2026-10-10 04:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TipoMercado',
            fields=[
                ('id_tipo_mercado', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_tipo', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'tipos_mercado',
            },
        ),
    ]
