# Generated by Django 6.1 on 2026-09-10 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contrato',
            fields=[
                ('id_contrato', models.AutoField(primary_key=True)),
                ('numero_cor', models.CharField(max_length=100)),
                ('institucion', models.CharField(max_length=100)),
                ('zona', models.CharField(max_length=100)),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField()),
                ('estado', models.CharField(max_length=50)),
            ],
        ),
    ]
