# Generated by Django 6.0.7 on 2026-09-12 03:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contratos_pae', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contrato',
            name='estado',
            field=models.CharField(default='Activo', max_length=50),
        ),
        migrations.AlterField(
            model_name='contrato',
            name='id_contrato',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
