# Generated by Django 6.1.1 on 2026-10-01 04:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contratos_pae', '0002_alter_contrato_estado_alter_contrato_id_contrato'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contrato',
            options={'managed': False},
        ),
    ]
