# Generated by Django 6.1.1 on 2026-10-01 21:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contratos_pae', '0003_alter_contrato_options'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='contrato',
            table='contrato_pae',
        ),
    ]
