# Generated by Django 6.0.7 on 2026-09-12 03:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Gramage',
            fields=[
                ('id_gramage', models.AutoField(primary_key=True, serialize=False)),
                ('id_ingrediente', models.IntegerField()),
                ('id_grado', models.IntegerField()),
                ('id_unidad_medida', models.IntegerField()),
                ('cantidad_gramage', models.DecimalField(decimal_places=2, max_digits=10)),
                ('descripcion', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'gramage_gramage',
                'managed': False,
            },
        ),
    ]
