# Generated by Django 6.1.1 on 2026-09-16 20:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ingredientes', '0002_remove_ingrediente_id_and_more'),
        ('platos', '0004_remove_plato_activo_remove_plato_descripcion_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='RecetaComponente',
            fields=[
                ('id_receta_componente', models.AutoField(primary_key=True, serialize=False)),
                ('cantidad', models.DecimalField(decimal_places=2, max_digits=10)),
                ('id_ingrediente', models.ForeignKey(db_column='id_ingrediente', on_delete=django.db.models.deletion.CASCADE, related_name='receta_componentes', to='ingredientes.ingrediente')),
                ('id_plato', models.ForeignKey(db_column='id_plato', on_delete=django.db.models.deletion.CASCADE, related_name='receta_componentes', to='platos.plato')),
            ],
            options={
                'verbose_name': 'Receta componente',
                'verbose_name_plural': 'Recetas componentes',
                'db_table': 'receta_componente',
                'managed': True,
            },
        ),
    ]
