# Generated by Django 6.1.1 on 2026-09-10 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SeccionMenu',
            fields=[
                ('id_seccion_menu', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100, unique=True, verbose_name='Nombre de la sección')),
                ('descripcion', models.TextField(blank=True, null=True, verbose_name='Descripción')),
                ('activo', models.BooleanField(default=True, verbose_name='¿Está activo?')),
            ],
            options={
                'verbose_name': 'Sección de Menú',
                'verbose_name_plural': 'Secciones de Menú',
                'db_table': 'secciones_menu',
            },
        ),
    ]
