# Generated by Django 6.1.1 on 2026-09-12 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('secciones_menu', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='seccionmenu',
            options={},
        ),
        migrations.RenameField(
            model_name='seccionmenu',
            old_name='id_seccion_menu',
            new_name='id_seccion',
        ),
        migrations.RemoveField(
            model_name='seccionmenu',
            name='activo',
        ),
        migrations.RemoveField(
            model_name='seccionmenu',
            name='descripcion',
        ),
        migrations.RemoveField(
            model_name='seccionmenu',
            name='nombre',
        ),
        migrations.AddField(
            model_name='seccionmenu',
            name='id_jornada',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='seccionmenu',
            name='nombre_seccion',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
