# Generated by Django 6.0.7 on 2026-09-12 03:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jornadas', '0001_initial'),
        ('secciones_menu', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='seccionmenu',
            options={'verbose_name': 'Sección de menú', 'verbose_name_plural': 'Secciones de menú'},
        ),
        migrations.RenameField(
            model_name='seccionmenu',
            old_name='id_seccion_menu',
            new_name='id_seccion',
        ),
        migrations.RemoveField(
            model_name='seccionmenu',
            name='activo',
        ),
        migrations.RemoveField(
            model_name='seccionmenu',
            name='descripcion',
        ),
        migrations.RemoveField(
            model_name='seccionmenu',
            name='nombre',
        ),
        migrations.AddField(
            model_name='seccionmenu',
            name='id_jornada',
            field=models.ForeignKey(blank=True, db_column='id_jornada', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='jornadas.jornada'),
        ),
        migrations.AddField(
            model_name='seccionmenu',
            name='nombre_seccion',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
