# Generated by Django 6.1.1 on 2026-09-16 00:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('secciones_menu', '0002_alter_seccionmenu_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='seccionmenu',
            options={'managed': True, 'verbose_name': 'Sección de menú', 'verbose_name_plural': 'Secciones de menú'},
        ),
    ]
