# Generated by Django 6.1.1 on 2026-10-01 04:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jornadas', '0002_alter_jornada_options'),
        ('secciones_menu', '0003_alter_seccionmenu_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seccionmenu',
            name='id_jornada',
            field=models.ForeignKey(blank=True, db_column='id_jornada', db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='jornadas.jornada'),
        ),
    ]
