# Generated by Django 6.1.1 on 2026-09-10 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UnidadMedida',
            fields=[
                ('id_unidad_medida', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50, unique=True, verbose_name='Nombre de la unidad')),
                ('abreviatura', models.CharField(max_length=10, unique=True, verbose_name='Abreviatura')),
                ('descripcion', models.CharField(blank=True, max_length=150, null=True, verbose_name='Descripción')),
            ],
            options={
                'verbose_name': 'Unidad de Medida',
                'verbose_name_plural': 'Unidades de Medida',
                'db_table': 'unidades_medida',
            },
        ),
    ]
