# Generated by Django 6.0.7 on 2026-09-12 03:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('unidades_medida', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='unidadmedida',
            options={},
        ),
        migrations.RemoveField(
            model_name='unidadmedida',
            name='descripcion',
        ),
        migrations.RemoveField(
            model_name='unidadmedida',
            name='nombre',
        ),
        migrations.AddField(
            model_name='unidadmedida',
            name='nombre_unidad',
            field=models.CharField(default='Sin nombre', max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='unidadmedida',
            name='abreviatura',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
