# Generated by Django 6.1.1 on 2026-09-16 00:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('unidades_medida', '0002_alter_unidadmedida_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='unidadmedida',
            options={'managed': True, 'verbose_name': 'Unidad de medida', 'verbose_name_plural': 'Unidades de medida'},
        ),
    ]
