# Generated by Django 6.1.1 on 2026-09-16 03:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('unidades_medida', '0003_alter_unidadmedida_options'),
        ('unidades_medida', '0004_reparar_tabla_unidades_final'),
    ]

    operations = [
    ]
