# Generated by Django 6.1.1 on 2026-09-26 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('unidades_medida', '0005_merge_20260915_2213'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='unidadmedida',
            options={},
        ),
        migrations.RemoveField(
            model_name='unidadmedida',
            name='nombre_unidad',
        ),
        migrations.AddField(
            model_name='unidadmedida',
            name='nombre',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='unidadmedida',
            name='abreviatura',
            field=models.CharField(default='', max_length=20),
            preserve_default=False,
        ),
    ]
