# Generated by Django 6.0.7 on 2026-09-12 03:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CategoriaInventario',
            fields=[
                ('id_categoria_inventario', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_categoria', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'categorias_inventario',
            },
        ),
    ]
