# Generated by Django 6.0.5 on 2026-09-10 05:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('turnos', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UsuarioTurno',
            fields=[
                ('id_usuario_turno', models.AutoField(primary_key=True, serialize=False)),
                ('fecha', models.DateField()),
                ('id_turno', models.ForeignKey(db_column='id_turno', on_delete=django.db.models.deletion.CASCADE, to='turnos.turno')),
                ('id_usuario_manipuladora', models.ForeignKey(db_column='id_usuario_manipuladora', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
