# Generated by Django 6.0.7 on 2026-09-12 03:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuario_turno', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='usuarioturno',
            table='usuario_turno',
        ),
    ]
