# Generated by Django 6.1.1 on 2026-10-01 04:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuario_turno', '0002_alter_usuarioturno_table'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='usuarioturno',
            options={'managed': False},
        ),
    ]
