# Generated by Django 6.1.1 on 2026-09-10 20:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('platos', '0001_initial'),
        ('unidades_medida', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DetallePlato',
            fields=[
                ('id_detalle_plato', models.AutoField(primary_key=True, serialize=False)),
                ('ingrediente', models.CharField(max_length=150, verbose_name='Nombre del Ingrediente / Insumo')),
                ('cantidad', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Cantidad')),
                ('observaciones', models.TextField(blank=True, null=True, verbose_name='Observaciones / Instrucciones')),
                ('id_plato', models.ForeignKey(db_column='id_plato', on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='platos.plato', verbose_name='Plato')),
                ('id_unidad_medida', models.ForeignKey(db_column='id_unidad_medida', on_delete=django.db.models.deletion.RESTRICT, related_name='detalles_plato', to='unidades_medida.unidadmedida', verbose_name='Unidad de Medida')),
            ],
            options={
                'verbose_name': 'Detalle de Plato',
                'verbose_name_plural': 'Detalles de Plato',
                'db_table': 'detalle_plato',
            },
        ),
    ]
