# Generated by Django 6.0.7 on 2026-09-12 03:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('detalle_plato', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='detalleplato',
            options={'managed': False},
        ),
    ]
