# Generated by Django 6.1.1 on 2026-09-16 00:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('detalle_plato', '0002_alter_detalleplato_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='detalleplato',
            options={'managed': True},
        ),
    ]
