# Generated by Django 6.1.1 on 2026-09-16 00:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('detalle_plato', '0003_alter_detalleplato_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='detalleplato',
            name='cantidad',
        ),
        migrations.RemoveField(
            model_name='detalleplato',
            name='id_unidad_medida',
        ),
        migrations.RemoveField(
            model_name='detalleplato',
            name='ingrediente',
        ),
        migrations.RemoveField(
            model_name='detalleplato',
            name='observaciones',
        ),
        migrations.AddField(
            model_name='detalleplato',
            name='estado_preparacion',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='detalleplato',
            name='id_menu',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='detalleplato',
            name='porcion_por_nino',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='detalleplato',
            name='total_a_preparar',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='detalleplato',
            name='unidad_total',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='detalleplato',
            name='id_plato',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
