# Generated by Django 6.1.1 on 2026-10-01 04:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('detalle_plato', '0004_remove_detalleplato_cantidad_and_more'),
        ('platos', '0005_alter_plato_id_seccion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detalleplato',
            name='id_plato',
            field=models.ForeignKey(blank=True, db_column='id_plato', db_constraint=False, null=True, on_delete=django.db.models.deletion.SET_NULL, to='platos.plato'),
        ),
    ]
