# Generated by Django 6.1 on 2026-09-11 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PreparacionAsignada',
            fields=[
                ('id_preparacion_asignada', models.AutoField(primary_key=True, serialize=False)),
                ('id_menu', models.IntegerField()),
                ('id_plato', models.IntegerField()),
                ('id_usuario_manipuladora', models.IntegerField()),
                ('id_turno', models.IntegerField()),
                ('fecha', models.DateField()),
                ('hora_programada', models.TimeField()),
                ('estado_preparacion', models.CharField(max_length=50)),
                ('observaciones', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'preparacion_asignada',
            },
        ),
    ]
