# Generated by Django 6.0.7 on 2026-09-12 03:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('preparacion_asignada', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='preparacionasignada',
            name='estado_preparacion',
            field=models.CharField(default='Pendiente', max_length=50),
        ),
    ]
