# Generated by Django 6.1.1 on 2026-10-01 04:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menus', '0002_alter_menu_id_jornada'),
        ('platos', '0005_alter_plato_id_seccion'),
        ('preparacion_asignada', '0002_alter_preparacionasignada_estado_preparacion'),
        ('turnos', '0002_alter_turno_hora_fin_alter_turno_hora_inicio_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='preparacionasignada',
            options={'managed': True},
        ),
        migrations.AlterField(
            model_name='preparacionasignada',
            name='estado_preparacion',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='preparacionasignada',
            name='fecha',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='preparacionasignada',
            name='hora_programada',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='preparacionasignada',
            name='id_menu',
            field=models.ForeignKey(blank=True, db_column='id_menu', db_constraint=False, null=True, on_delete=django.db.models.deletion.CASCADE, to='menus.menu'),
        ),
        migrations.AlterField(
            model_name='preparacionasignada',
            name='id_plato',
            field=models.ForeignKey(blank=True, db_column='id_plato', db_constraint=False, null=True, on_delete=django.db.models.deletion.CASCADE, to='platos.plato'),
        ),
        migrations.AlterField(
            model_name='preparacionasignada',
            name='id_turno',
            field=models.ForeignKey(blank=True, db_column='id_turno', db_constraint=False, null=True, on_delete=django.db.models.deletion.CASCADE, to='turnos.turno'),
        ),
        migrations.AlterField(
            model_name='preparacionasignada',
            name='id_usuario_manipuladora',
            field=models.ForeignKey(blank=True, db_column='id_usuario_manipuladora', db_constraint=False, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
