# Generated by Django 6.0.5 on 2026-09-10 03:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ingrediente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_ingrediente', models.CharField(max_length=100)),
                ('descripcion', models.TextField()),
                ('imagen_ingrediente', models.CharField(max_length=255)),
                ('marca_ingrediente', models.CharField(max_length=100)),
            ],
        ),
    ]
