# Generated by Django 6.0.7 on 2026-09-12 03:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categorias_inventario', '0001_initial'),
        ('ingredientes', '0001_initial'),
        ('unidades_medida', '0002_alter_unidadmedida_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ingrediente',
            name='id',
        ),
        migrations.AddField(
            model_name='ingrediente',
            name='id_categoria_inventario',
            field=models.ForeignKey(blank=True, db_column='id_categoria_inventario', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='categorias_inventario.categoriainventario'),
        ),
        migrations.AddField(
            model_name='ingrediente',
            name='id_ingrediente',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AddField(
            model_name='ingrediente',
            name='id_unidad_medida',
            field=models.ForeignKey(blank=True, db_column='id_unidad_medida', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='unidades_medida.unidadmedida'),
        ),
        migrations.AlterField(
            model_name='ingrediente',
            name='descripcion',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='ingrediente',
            name='imagen_ingrediente',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='ingrediente',
            name='marca_ingrediente',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='ingrediente',
            name='nombre_ingrediente',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterModelTable(
            name='ingrediente',
            table='ingredientes',
        ),
    ]
