# Generated by Django 6.0.7 on 2026-09-12 03:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('jornadas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id_menu', models.AutoField(primary_key=True, serialize=False)),
                ('fecha', models.DateField()),
                ('ninos_presentes', models.IntegerField()),
                ('estado', models.CharField(max_length=50)),
                ('informacion_nutricional', models.TextField()),
                ('id_contrato', models.IntegerField()),
                ('id_jornada', models.ForeignKey(db_column='id_jornada', on_delete=django.db.models.deletion.CASCADE, to='jornadas.jornada')),
            ],
            options={
                'db_table': 'menus',
            },
        ),
    ]
