# Generated by Django 6.1.1 on 2026-10-01 04:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jornadas', '0002_alter_jornada_options'),
        ('menus', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu',
            name='id_jornada',
            field=models.ForeignKey(db_column='id_jornada', db_constraint=False, on_delete=django.db.models.deletion.CASCADE, to='jornadas.jornada'),
        ),
    ]
